services:
  runner:
    image: ghcr.io/leg3/svraas-runner@sha256:d95364e17ab6c46927129ddb8b46ab8718a00e8b700888a2b22cf3fff262d5a9

    environment:
      SVRAAS_ARTIFACT_ROOT: /artifacts
      SVRAAS_CHECK_INTERVAL: "60"
      SVRAAS_RETRY_INTERVAL: "3600"

    secrets:
      - fred_key

    volumes:
      - artifacts:/artifacts

    deploy:
      replicas: 1

      restart_policy:
        condition: any
        delay: 5s

      update_config:
        parallelism: 1
        order: stop-first

volumes:
  artifacts:
    driver: local
    driver_opts:
      type: nfs
      o: addr=127.0.0.1,nfsvers=4.1,rw
      device: :/artifacts

secrets:
  fred_key:
    external: true
