NFS_CORE_PARAM {
    Protocols = 4;
    NFS_Port = 2049;
    Enable_NLM = false;
    Enable_RQUOTA = false;
    Enable_UDP = false;
    Allow_Set_Io_Flusher_Fail = true;
}

NFSV4 {
    Minor_Versions = 1;
}

EXPORT {
    Export_Id = 1;
    Path = /export/artifacts;
    Pseudo = /artifacts;

    Access_Type = RW;
    Squash = Root_Squash;
    Anonymous_uid = 65534;
    Anonymous_gid = 65534;
    SecType = sys;
    Protocols = 4;
    Transports = TCP;

    FSAL {
        Name = VFS;
    }
}
