NFS_CORE_PARAM {
    Protocols = 4;
    NFS_Port = 2049;
    Allow_Set_Io_Flusher_Fail = true;
}

NFSV4 {
    Minor_Versions = 1;
}

EXPORT {
    Export_Id = 1;
    Path = /export/artifacts;
    Pseudo = /artifacts;

    Access_Type = RW;
    Squash = Root_Squash;
    SecType = sys;
    Protocols = 4;
    Transports = TCP;

    FSAL {
        Name = VFS;
    }
}
